blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("all/", views.all_post_list, name="all_post_list"),
    path("create/", views.post_create, name="post_create"),
    path("<int:pk>/", views.post_detail, name="post_detail"),
    path("<int:pk>/update/", views.post_update, name="post_update"),
    path("<int:pk>/delete/", views.post_delete, name="post_delete"),
    path("<int:pk>/comment/", views.comment_create, name="comment_create"),
    path("comment/<int:pk>/update/", views.comment_update, name="comment_update"),
    path("comment/<int:pk>/delete/", views.comment_delete, name="comment_delete"),
    path("category/", views.category_list, name="category_list"),
    path("category/create/", views.category_create, name="category_create"),
    path("category/<int:pk>/update/", views.category_update, name="category_update"),
    path("category/<int:pk>/delete/", views.category_delete, name="category_delete"),
    path("tag/<str:tag_name>/", views.tag_list, name="tag_list"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("blog/", include("blog.urls")),
    path("accounts/", include("accounts.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User


# 카테고리 모델
class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "카테고리"
        verbose_name_plural = "카테고리 그룹"

    def __str__(self):
        return self.name


# 태그 모델
class Tag(models.Model):
    name = models.CharField(max_length=40, unique=True)

    class Meta:
        verbose_name = "태그"
        verbose_name_plural = "태그 그룹"

    def __str__(self):
        return self.name


# 게시글 모델
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    categories = models.ManyToManyField(Category, blank=True, related_name="post_categories")
    tags = models.ManyToManyField(Tag, blank=True, related_name="post_tags")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "포스트"
        verbose_name_plural = "포스트 그룹"
        ordering = ["-created_at"]


    def __str__(self):
        return self.title


class Image(models.Model):
    post = models.ForeignKey(Post, default=None, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to="blog/%Y/%m/%d/")

    class Meta:
        verbose_name = "이미지"
        verbose_name_plural = "이미지 그룹"

    def __str__(self):
        return f"{self.post.title} - Image {self.id}"


# 댓글 모델
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "댓글"
        verbose_name_plural = "댓글 그룹"

    def __str__(self):
        return self.content

templates/posts/all_post_list.html
{% extends "base.html" %}

{% block head %}
<style>
    .card-img-top {
        max-width: 100%;
        max-height: 200px;
        object-fit: cover;
    }
</style>
{% endblock %}

{% block content %}
<div class="container py-5">
    <h1 class="mb-4">전체 게시글 목록</h1>
    <form class="d-inline-flex" role="search" action="" method="get">
        <input name="q" class="form-control me-2" type="search" placeholder="키워드를 입력해주세요." aria-label="Search">
        <button class="btn btn-outline-success py-2 px-4 text-nowrap" type="submit">검색</button>
    </form>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4 mt-4">
    {% for post in posts %}
        <div class="col">
            <div class="card h-100">
            {% with post.images.first as image %}
                {% if image %}
                <img src="{{ image.image.url }}" class="card-img-top" alt="{{ post.title }}">
                {% else %}
                <img src="https://cdn.pixabay.com/photo/2015/06/19/21/24/avenue-815297_1280.jpg" class="card-img-top"
                    alt="Default Image">
                {% endif %}
            {% endwith %}
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.content|truncatewords:20 }}</p>
                </div>
                <div class="card-footer d-flex justify-content-between align-items-center">
                    <div>
                        <small class="text-muted">작성자: {{ post.author.username }}</small><br>
                        <small class="text-muted">작성일: {{ post.created_at|date:"Y-m-d" }}</small>
                    </div>
                    <a href="{% url "post_detail" post.pk %}" class="btn btn-dark">자세히 보기</a>
                </div>
            </div>
        </div>
        {% empty %}
        <p>게시글이 없습니다.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/posts/post_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-3">
    <h1>게시글 삭제 확인</h1>
    <p>정말로 아래의 게시글을 삭제하시겠습니까?</p>

    <div class="alert alert-danger" role="alert">
        <strong>제목:</strong> {{ object.title }}<br>
        <strong>작성자:</strong> {{ object.author }}<br>
        <strong>작성일:</strong> {{ object.created_at }}<br>
        <strong>내용 미리보기:</strong> {{ object.content|truncatewords:30 }}
    </div>

    <form action="" method="post">{% csrf_token %}
        <a href="{% url 'post_list' %}" class="btn btn-secondary">취소</a>
        <button type="submit" class="btn btn-danger">삭제 확인</button>
    </form>
</div>
{% endblock %}

templates/posts/post_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
  <div class="border border-2 p-4 rounded">
    <article>
      <header class="mb-4">
        <h1 class="fw-bolder my-3">{{ post.title }}</h1>
        <div class="text-muted fs-5 fw-semibold mb-2">- {{ post.author.username }}</div>
        <div class="text-muted fw-light mb-2">작성일: {{ post.created_at|date:"Y-m-d" }} / 최종수정일: {{ post.updated_at|date:"Y-m-d" }}</div>
        {% if user.is_authenticated and user == post.author %}
        <hr>
        <div>
          <a href="{% url "post_update" post.pk %}" class="btn btn-outline-secondary btn-sm">수정</a>
          <a href="{% url "post_delete" post.pk %}" class="btn btn-outline-danger btn-sm">삭제</a>
        </div>
        {% endif %}
      </header>
      <section class="post-content mb-4">
        <p class="fs-5 fw-medium">{{ post.content }}</p>
      </section>

      {% if post.tags.exists %}
      <p>
        <strong>Tags:</strong>
        {% for tag in post.tags.all %}
        <a href="{% url "tag_list" tag.name %}" class="badge rounded-pill text-bg-warning">{{ tag.name }}</a>
        {% endfor %}
      </p>
      {% endif %}

      {% if post.images.exists %}
      <div class="mb-4">
        <h3>Images</h3>
        <div class="row g-2">
          {% for image in post.images.all %}
          <div class="col-md-4 col-lg-3">
            <a href="{{ image.image.url }}" data-bs-toggle="lightbox" data-gallery="post-images"
              data-title="{{ post.title }}" data-alt="{{ post.title }}">
              <img src="{{ image.image.url }}" class="img-fluid rounded" alt="{{ post.title }}">
            </a>
          </div>
          {% endfor %}
        </div>
      </div>
      {% else %}
      <div class="mb-4">
        <h3>Images</h3>
        <p>이미지가 없습니다.</p>
      </div>
      {% endif %}
    </article>

    <section class="comments mt-5">
      <h3>Comments ({{ post.comments.count }})</h3>
      {% for comment in post.comments.all %}
      <div class="card mb-3">
        <div class="card-body">
          <p class="card-text">{{ comment.content }}</p>
          <footer class="blockquote-footer">{{ comment.author.username }} on <cite title="Source Title">{{comment.updated_at|date:"Y-m-d H:i" }}</cite></footer>
          {% if user.is_authenticated and user == comment.author %}
          <div>
            <a href="{% url "comment_update" comment.pk %}" class="btn btn-outline-secondary btn-sm">수정</a>
            <a href="{% url "comment_delete" comment.pk %}" class="btn btn-outline-danger btn-sm">삭제</a>
          </div>
          {% endif %}
        </div>
      </div>
      {% endfor %}
    </section>

    {% if user.is_authenticated %}
    <div class="add-comment mt-4">
      <form method="post">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <button type="submit" class="btn btn-primary">댓글 저장</button>
      </form>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/posts/post_form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
<div class="container mt-5">
  <h2>{{ view.title }}</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row mb-3">
      <div class="col-md-9">
        <label for="title" class="form-label">제목</label>
        {{ form.title|add_class:"form-control" }}
      </div>
      <div class="col-md-3">
        <label for="id_categories" class="form-label">카테고리</label>
        <select name="categories" class="form-select" id="id_categories">
          {% for category in form.categories.field.queryset %}
          <option value="{{ category.id }}">{{ category.name }}</option>
          {% endfor %}
        </select>
      </div>
    </div>
    <div class="mb-3">
      <label for="content" class="form-label">내용</label>
      {{ form.content|add_class:"form-control" }}
    </div>
    <div class="mb-3">
      <label for="tags" class="form-label">태그</label>
      {{ form.tags|add_class:"form-control" }}
      <div id="tagsHelp" class="form-text">태그는 '#'으로 구분하여 입력하세요.</div>
    </div>
    <div class="mb-3">
      <label class="form-label">이미지</label>
      {{ image_formset.management_form }}
      {% for form in image_formset %}
      <div class="mb-3">
        {{ form.id }}
        <div class="form-check">
          {{ form.DELETE|add_class:"form-check-input" }}
          <label class="form-check-label" for="{{ form.DELETE.id_for_label }}">삭제</label>
        </div>
        {{ form.image|add_class:"form-control" }}
        {% if form.instance.image %}
        <img src="{{ form.instance.image.url }}" width="100" alt="Image">
        {% endif %}
      </div>
      {% if image_formset_errors %}
      <div class="alert alert-danger">
        <strong>이미지 폼셋 오류:</strong>
        {% for error in image_formset_errors %}
        <p>{{ error }}</p>
        {% endfor %}
      </div>
      {% endif %}
      {% endfor %}
    </div>
    <button type="submit" class="btn btn-primary">저장</button>
  </form>
</div>
{% endblock %}

templates/posts/post_list.html
{% extends "base.html" %}

{% block head %}
<style>
  .card-img-top {
    max-width: 100%;
    max-height: 200px;
    object-fit: cover;
  }
</style>
{% endblock %}

{% block content %}
<div class="container py-5">
  <h1 class="mb-4">{{ user.username }} 님의 게시글 목록</h1>
  <form class="d-inline-flex" role="search" action="" method="get">
    <input name="q" class="form-control me-2" type="search" placeholder="키워드를 입력해주세요." aria-label="Search">
    <button class="btn btn-outline-success py-2 px-4 text-nowrap" type="submit">검색</button>
  </form>
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4 mt-4">
    {% for post in posts %}
    <div class="col">
      <div class="card h-100">
        {% with post.images.first as image %}
          {% if image %}
          <img src="{{ image.image.url }}" class="card-img-top" alt="{{ post.title }}">
          {% else %}
          <img src="https://cdn.pixabay.com/photo/2015/06/19/21/24/avenue-815297_1280.jpg" class="card-img-top" alt="Default Image">
          {% endif %}
        {% endwith %}
        <div class="card-body">
          <h5 class="card-title">{{ post.title }}</h5>
          <p class="card-text">{{ post.content|truncatewords:20 }}</p>
        </div>
        <div class="card-footer d-flex justify-content-between align-items-center">
          <div>
            <small class="text-muted">작성자: {{ post.author.username }}</small><br>
            <small class="text-muted">작성일: {{ post.created_at|date:"Y-m-d" }}</small>
          </div>
          <a href="{% url "post_detail" post.pk %}" class="btn btn-dark">자세히 보기</a>
        </div>
      </div>
    </div>
    {% empty %}
    <p>게시글이 없습니다.</p>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/posts/tag_list.html
{% extends "base.html" %}

{% block head %}
<style>
    .card-img-top {
        max-width: 100%;
        max-height: 200px;
        object-fit: cover;
    }
</style>
{% endblock %}

{% block content %}
<div class="container py-5">
    <h1 class="mb-4">"{{ tag_name }}" 태그가 포함된 게시글</h1>
    <hr>
    <h4>({{ posts_counted }}) 개의 게시글이 검색되었습니다.</h4>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4 mt-4">
        {% for post in posts %}
        <div class="col">
            <div class="card h-100">
                {% with post.images.first as image %}
                    {% if image %}
                    <img src="{{ image.image.url }}" class="card-img-top" alt="{{ post.title }}">
                    {% else %}
                    <img src="https://cdn.pixabay.com/photo/2015/06/19/21/24/avenue-815297_1280.jpg" class="card-img-top" alt="Default Image">
                    {% endif %}
                {% endwith %}    
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.content|truncatewords:20 }}</p>
                </div>
                <div class="card-footer d-flex justify-content-between align-items-center">
                    <div>
                        <small class="text-muted">작성자: {{ post.author.username }}</small><br>
                        <small class="text-muted">작성일: {{ post.created_at|date:"Y-m-d" }}</small>
                    </div>
                    <a href="{% url "post_detail" post.pk %}" class="btn btn-dark">자세히 보기</a>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col">
            <p>해당 태그를 포함하는 게시글이 없습니다.</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}